version: "3.7"

services:
  tool-index:
    container_name: tool-index-api
    build:
      context: ../
      dockerfile: docker/docker.development.dockerfile
      target: development
    image: tool-index
    init: true
    restart: unless-stopped
    environment:
      NODE_ENV: development
      DB_HOST: mongodb://mongo:27017/tool-index
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - tool-index-network
    volumes:
      - ../:/app/tool-index
  mongo:
    container_name: mongo
    image: mongo
    init: true
    restart: unless-stopped
    networks:
      - tool-index-network
    volumes:
      - ../db-data:/data/db
    command: mongod --noauth
    ports:
      - "27017:27017"

networks:
  tool-index-network:
